### ISSUE TITLE
FileNotFoundError when using getItems

### ISSUE THREAD

**Issue by mkreuz** [Socvest/streamlit-browser-session-storage#1]
Hi, I really appreciate this package as it allows to use the session storage, especially for storing login status.

It was tough to get the package to work (same default key is used), but I encountered another issue which I was not able to resolve.

```
2023-12-20 12:11:14.766 ComponentRequestHandler: GET /.../lib/python3.12/site-packages/streamlit_session_browser_storage/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
  File "/.../lib/python3.12/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get
    with open(abspath, "rb") as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/markus.kreuz/anaconda3/envs/recon-dashboard/lib/python3.12/site-packages/streamlit_session_browser_storage/frontend/build/bootstrap.min.css.map'
```

The application seems to work, but it is nice to have a clean log

**Comment by Socvest** [comment]
Hey, sorry for the late response. So about getting the stored key, I have simplified it in the latest update. It returns a dictionary of the key value you stored. Regarding the module not found, I get it too, not sure why. Read somewhere it tends to occur when the console or the browser "inspect" has been clicked. But not entirely sure.

**Comment by Socvest** [comment]
**Update**

It seems its only relevant when the dev tools are open (so when you wanted to see the storage you opened the dev and hence it showed up) explained [here](https://stackoverflow.com/a/21773495) and [here](https://stackoverflow.com/a/49273495). It does not seem to be in the original streamlit custom components file but will add in future updates.

**Comment by Socvest** [comment]
**Update**

The `.map` file has been added to the latest version.

**Comment by mkreuz** [comment]
Thanks for the Info, I will try this
